import { ResultRow } from "@/components/ResultRow";
import { SectionCard } from "@/components/SectionCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  useCalcPos,
  useCalcProfit,
  useCreateInvoice,
} from "@/hooks/useQueries";
import jsPDF from "jspdf";
import {
  CreditCard,
  Download,
  FileText,
  LogOut,
  TrendingUp,
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

interface AppPageProps {
  onLogout: () => void;
}

export function AppPage({ onLogout }: AppPageProps) {
  // Invoice state
  const [clientName, setClientName] = useState("");
  const [amount, setAmount] = useState("");
  const [discount, setDiscount] = useState("");
  const [invoiceResult, setInvoiceResult] = useState<{
    client: string;
    amount: number;
    discount: number;
    total: number;
  } | null>(null);

  // POS state
  const [posAmount, setPosAmount] = useState("");
  const [posResult, setPosResult] = useState<{
    fee: number;
    total: number;
  } | null>(null);

  // Profit state
  const [cost, setCost] = useState("");
  const [sell, setSell] = useState("");
  const [profitResult, setProfitResult] = useState<{ profit: number } | null>(
    null,
  );

  const createInvoice = useCreateInvoice();
  const calcPos = useCalcPos();
  const calcProfit = useCalcProfit();

  function fmt(n: number) {
    return n.toLocaleString("en-US", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    });
  }

  async function handleGenerateInvoice() {
    if (!clientName.trim()) {
      toast.error("Please enter a client name.");
      return;
    }
    const a = Math.round(Number.parseFloat(amount) || 0);
    const d = Math.round(Number.parseFloat(discount) || 0);
    if (a < 0 || d < 0) {
      toast.error("Amount and discount must be positive.");
      return;
    }
    try {
      await createInvoice.mutateAsync({
        client: clientName.trim(),
        amount: BigInt(a),
        discount: BigInt(d),
      });
      const total = a - d;
      setInvoiceResult({
        client: clientName.trim(),
        amount: a,
        discount: d,
        total,
      });
      toast.success("Invoice saved successfully.");
    } catch {
      // fallback: calculate locally if actor not ready
      const total = a - d;
      setInvoiceResult({
        client: clientName.trim(),
        amount: a,
        discount: d,
        total,
      });
    }
  }

  function handleDownloadInvoice() {
    if (!invoiceResult) {
      toast.error("Generate an invoice first.");
      return;
    }
    const { client, amount: a, discount: d, total } = invoiceResult;
    const date = new Date().toLocaleDateString("en-US");

    const doc = new jsPDF({ unit: "mm", format: "a4" });

    // Header bar
    doc.setFillColor(17, 24, 39); // dark navy
    doc.rect(0, 0, 210, 30, "F");
    doc.setTextColor(34, 197, 94); // green accent
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("InvoicePro X", 14, 19);

    // Title
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text("INVOICE", 14, 44);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(`Date: ${date}`, 14, 52);

    // Divider
    doc.setDrawColor(220, 220, 220);
    doc.line(14, 57, 196, 57);

    // Client
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Bill To:", 14, 66);
    doc.setFont("helvetica", "normal");
    doc.text(client, 14, 73);

    // Table header
    doc.setFillColor(243, 244, 246);
    doc.rect(14, 82, 182, 9, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text("Description", 17, 88.5);
    doc.text("Amount", 175, 88.5, { align: "right" });

    // Rows
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    doc.text("Subtotal", 17, 99);
    doc.text(`$${fmt(a)}`, 175, 99, { align: "right" });
    doc.text("Discount", 17, 109);
    doc.setTextColor(220, 50, 50);
    doc.text(`-$${fmt(d)}`, 175, 109, { align: "right" });

    // Total row
    doc.setDrawColor(220, 220, 220);
    doc.line(14, 114, 196, 114);
    doc.setFillColor(17, 24, 39);
    doc.rect(14, 116, 182, 12, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(34, 197, 94);
    doc.text("TOTAL", 17, 124.5);
    doc.text(`$${fmt(total)}`, 175, 124.5, { align: "right" });

    // Footer note
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(160, 160, 160);
    doc.text("Generated by InvoicePro X · caffeine.ai", 105, 285, {
      align: "center",
    });

    const fileName = `invoice-${client.replace(/\s+/g, "-").toLowerCase()}.pdf`;
    doc.save(fileName);
    toast.success("Invoice PDF downloaded.");
  }

  async function handleCalcPos() {
    const a = Math.round(Number.parseFloat(posAmount) || 0);
    if (a <= 0) {
      toast.error("Enter a valid transaction amount.");
      return;
    }
    try {
      const result = await calcPos.mutateAsync({ amount: BigInt(a) });
      setPosResult({ fee: Number(result.fee), total: Number(result.total) });
    } catch {
      // fallback
      const fee = a * 0.02;
      setPosResult({ fee, total: a + fee });
    }
  }

  async function handleCalcProfit() {
    const c = Math.round(Number.parseFloat(cost) || 0);
    const s = Math.round(Number.parseFloat(sell) || 0);
    if (c < 0 || s < 0) {
      toast.error("Enter valid cost and sell prices.");
      return;
    }
    try {
      const result = await calcProfit.mutateAsync({
        cost: BigInt(c),
        sell: BigInt(s),
      });
      setProfitResult({ profit: Number(result.profit) });
    } catch {
      setProfitResult({ profit: s - c });
    }
  }

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Header */}
      <header className="bg-card border-b border-border sticky top-0 z-10 shadow-xs">
        <div className="max-w-[460px] mx-auto px-4 h-14 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-xl">📄</span>
            <span className="font-display font-bold text-foreground text-lg">
              InvoicePro <span className="text-primary">X</span>
            </span>
          </div>
          <Button
            variant="ghost"
            size="sm"
            onClick={onLogout}
            className="text-muted-foreground hover:text-foreground hover:bg-muted/50 transition-smooth"
            data-ocid="logout-btn"
          >
            <LogOut className="w-4 h-4 mr-1" />
            <span className="text-xs font-display">Logout</span>
          </Button>
        </div>
      </header>

      {/* Main */}
      <main className="flex-1 py-6 px-4">
        <div className="max-w-[420px] mx-auto space-y-4">
          {/* Invoice Section */}
          <SectionCard title="Invoice Generator" icon="🧾">
            <div className="space-y-3">
              <div className="space-y-1">
                <Label
                  htmlFor="client"
                  className="text-xs text-muted-foreground font-display"
                >
                  Client Name
                </Label>
                <Input
                  id="client"
                  placeholder="e.g. Acme Corp"
                  value={clientName}
                  onChange={(e) => setClientName(e.target.value)}
                  className="bg-input border-border text-foreground placeholder:text-muted-foreground text-sm"
                  data-ocid="invoice-client"
                />
              </div>
              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-1">
                  <Label
                    htmlFor="amount"
                    className="text-xs text-muted-foreground font-display"
                  >
                    Amount ($)
                  </Label>
                  <Input
                    id="amount"
                    type="number"
                    placeholder="0.00"
                    min="0"
                    value={amount}
                    onChange={(e) => setAmount(e.target.value)}
                    className="bg-input border-border text-foreground placeholder:text-muted-foreground text-sm"
                    data-ocid="invoice-amount"
                  />
                </div>
                <div className="space-y-1">
                  <Label
                    htmlFor="discount"
                    className="text-xs text-muted-foreground font-display"
                  >
                    Discount ($)
                  </Label>
                  <Input
                    id="discount"
                    type="number"
                    placeholder="0.00"
                    min="0"
                    value={discount}
                    onChange={(e) => setDiscount(e.target.value)}
                    className="bg-input border-border text-foreground placeholder:text-muted-foreground text-sm"
                    data-ocid="invoice-discount"
                  />
                </div>
              </div>
              <Button
                onClick={handleGenerateInvoice}
                disabled={createInvoice.isPending}
                className="w-full bg-primary text-primary-foreground hover:bg-primary/90 font-display font-semibold transition-smooth"
                data-ocid="invoice-generate-btn"
              >
                <FileText className="w-4 h-4 mr-2" />
                {createInvoice.isPending ? "Saving…" : "Generate Invoice"}
              </Button>

              {invoiceResult && (
                <div className="space-y-1.5 pt-1" data-ocid="invoice-result">
                  <ResultRow label="Client" value={invoiceResult.client} />
                  <ResultRow
                    label="Amount"
                    value={`$${fmt(invoiceResult.amount)}`}
                  />
                  <ResultRow
                    label="Discount"
                    value={`-$${fmt(invoiceResult.discount)}`}
                  />
                  <ResultRow
                    label="Total"
                    value={`$${fmt(invoiceResult.total)}`}
                    highlight
                  />
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleDownloadInvoice}
                    className="w-full mt-1 border-border text-foreground hover:bg-muted/50 font-display transition-smooth"
                    data-ocid="invoice-download-btn"
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Download Invoice
                  </Button>
                </div>
              )}
            </div>
          </SectionCard>

          {/* Divider */}
          <div className="border-t border-border/50" />

          {/* POS Section */}
          <SectionCard title="POS Fee Calculator" icon="💳">
            <div className="space-y-3">
              <div className="space-y-1">
                <Label
                  htmlFor="pos-amount"
                  className="text-xs text-muted-foreground font-display"
                >
                  Transaction Amount ($)
                </Label>
                <Input
                  id="pos-amount"
                  type="number"
                  placeholder="0.00"
                  min="0"
                  value={posAmount}
                  onChange={(e) => setPosAmount(e.target.value)}
                  className="bg-input border-border text-foreground placeholder:text-muted-foreground text-sm"
                  data-ocid="pos-amount"
                />
              </div>
              <Button
                onClick={handleCalcPos}
                disabled={calcPos.isPending}
                className="w-full bg-primary text-primary-foreground hover:bg-primary/90 font-display font-semibold transition-smooth"
                data-ocid="pos-calc-btn"
              >
                <CreditCard className="w-4 h-4 mr-2" />
                {calcPos.isPending ? "Calculating…" : "Calculate POS Fee"}
              </Button>

              {posResult && (
                <div className="space-y-1.5 pt-1" data-ocid="pos-result">
                  <ResultRow
                    label="Platform Fee (2%)"
                    value={`$${fmt(posResult.fee)}`}
                  />
                  <ResultRow
                    label="Total Charge"
                    value={`$${fmt(posResult.total)}`}
                    highlight
                  />
                </div>
              )}
            </div>
          </SectionCard>

          {/* Divider */}
          <div className="border-t border-border/50" />

          {/* Profit Section */}
          <SectionCard title="Profit Calculator" icon="📈">
            <div className="space-y-3">
              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-1">
                  <Label
                    htmlFor="cost-price"
                    className="text-xs text-muted-foreground font-display"
                  >
                    Cost Price ($)
                  </Label>
                  <Input
                    id="cost-price"
                    type="number"
                    placeholder="0.00"
                    min="0"
                    value={cost}
                    onChange={(e) => setCost(e.target.value)}
                    className="bg-input border-border text-foreground placeholder:text-muted-foreground text-sm"
                    data-ocid="profit-cost"
                  />
                </div>
                <div className="space-y-1">
                  <Label
                    htmlFor="sell-price"
                    className="text-xs text-muted-foreground font-display"
                  >
                    Sell Price ($)
                  </Label>
                  <Input
                    id="sell-price"
                    type="number"
                    placeholder="0.00"
                    min="0"
                    value={sell}
                    onChange={(e) => setSell(e.target.value)}
                    className="bg-input border-border text-foreground placeholder:text-muted-foreground text-sm"
                    data-ocid="profit-sell"
                  />
                </div>
              </div>
              <Button
                onClick={handleCalcProfit}
                disabled={calcProfit.isPending}
                className="w-full bg-primary text-primary-foreground hover:bg-primary/90 font-display font-semibold transition-smooth"
                data-ocid="profit-calc-btn"
              >
                <TrendingUp className="w-4 h-4 mr-2" />
                {calcProfit.isPending ? "Calculating…" : "Calculate Profit"}
              </Button>

              {profitResult !== null && (
                <div className="space-y-1.5 pt-1" data-ocid="profit-result">
                  <ResultRow
                    label="Net Profit"
                    value={`${profitResult.profit >= 0 ? "+" : ""}$${fmt(profitResult.profit)}`}
                    highlight
                  />
                  {cost && sell && Number.parseFloat(sell) > 0 && (
                    <ResultRow
                      label="Margin"
                      value={`${fmt((profitResult.profit / Number.parseFloat(sell)) * 100)}%`}
                    />
                  )}
                </div>
              )}
            </div>
          </SectionCard>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-card border-t border-border py-4 mt-4">
        <div className="max-w-[420px] mx-auto px-4 text-center">
          <p className="text-xs text-muted-foreground font-body">
            © {new Date().getFullYear()}.{" "}
            <a
              href={`https://caffeine.ai?utm_source=caffeine-footer&utm_medium=referral&utm_content=${encodeURIComponent(typeof window !== "undefined" ? window.location.hostname : "")}`}
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-primary transition-colors duration-200"
            >
              Built with love using caffeine.ai
            </a>
          </p>
        </div>
      </footer>
    </div>
  );
}
