/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PosResult = IDL.Record({ 'fee' : IDL.Nat, 'total' : IDL.Nat });
export const ProfitResult = IDL.Record({ 'profit' : IDL.Int });
export const InvoiceId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Invoice = IDL.Record({
  'id' : InvoiceId,
  'client' : IDL.Text,
  'total' : IDL.Nat,
  'createdAt' : Timestamp,
  'discount' : IDL.Nat,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'calcPos' : IDL.Func([IDL.Nat], [PosResult], ['query']),
  'calcProfit' : IDL.Func([IDL.Nat, IDL.Nat], [ProfitResult], ['query']),
  'createInvoice' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Invoice], []),
  'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PosResult = IDL.Record({ 'fee' : IDL.Nat, 'total' : IDL.Nat });
  const ProfitResult = IDL.Record({ 'profit' : IDL.Int });
  const InvoiceId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Invoice = IDL.Record({
    'id' : InvoiceId,
    'client' : IDL.Text,
    'total' : IDL.Nat,
    'createdAt' : Timestamp,
    'discount' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'calcPos' : IDL.Func([IDL.Nat], [PosResult], ['query']),
    'calcProfit' : IDL.Func([IDL.Nat, IDL.Nat], [ProfitResult], ['query']),
    'createInvoice' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Invoice], []),
    'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };