/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Invoice {
  'id' : InvoiceId,
  'client' : string,
  'total' : bigint,
  'createdAt' : Timestamp,
  'discount' : bigint,
  'amount' : bigint,
}
export type InvoiceId = bigint;
export interface PosResult { 'fee' : bigint, 'total' : bigint }
export interface ProfitResult { 'profit' : bigint }
export type Timestamp = bigint;
export interface _SERVICE {
  'calcPos' : ActorMethod<[bigint], PosResult>,
  'calcProfit' : ActorMethod<[bigint, bigint], ProfitResult>,
  'createInvoice' : ActorMethod<[string, bigint, bigint], Invoice>,
  'listInvoices' : ActorMethod<[], Array<Invoice>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];